//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class islemler
    {
        public int islemno { get; set; }
        public string islemiyapan_nick { get; set; }
        public int boy { get; set; }
        public int kilo { get; set; }
        public string sonuc { get; set; }
    }
}
